### ISSUE TITLE
Nice Theme

### ISSUE THREAD

**Issue by christianhaitian** [pix33l/es-theme-pix3l#1]
Hi,

I like this theme quite a bit.  Any concern if I include it in future ArkOS images for 3:2 devices like the V10?

Thanks,

**Comment by pix33l** [comment]
Hi，chris

Wow, of course. I'm sorry that I haven't paid attention to GitHub's push recently. It's my honor to add it to ArkOS.

And thank you for liking it.

**Comment by pix33l** [comment]
> Hi,
> 
> 
> 
> I like this theme quite a bit.  Any concern if I include it in future ArkOS images for 3:2 devices like the V10?
> 
> 
> 
> Thanks,

At present, it has only been tested in V10 (3:2), because I haven't bought other resolution devices.😆

**Comment by christianhaitian** [comment]
Awesome and no worries.  Thank you again for your work on this.
